apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    path: pki/sign/example-dot-com
    server: http://vault.demo.svc:8200
    auth:
      kubernetes:
        role: "vault-issuer"
        mountPath: /v1/auth/kubernetes
        serviceAccountRef:
          name: vault-issuer
