apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: m4
  namespace: demo
spec:
  version: "4.4.26"
  terminationPolicy: WipeOut
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  sslMode: requireSSL
  tls:
    issuerRef:
      apiGroup: "cert-manager.io"
      kind: ClusterIssuer
      name: vault-issuer
  clusterAuthMode: x509
  monitor:
    agent: prometheus.io/builtin
  #   agent: prometheus.io/operator
  #   prometheus:
  #     serviceMonitor:
  #       labels:
  #         release: kube-prometheus-stack
