# https://github.com/bytebuilders/installer/blob/master/charts/service-presets/templates/vault/issuer.yaml

# https://developer.hashicorp.com/vault/tutorials/kubernetes/kubernetes-cert-manager#deploy-cert-manager

apiVersion: policy.kubevault.com/v1alpha1
kind: VaultPolicy
metadata:
  name: vault-issuer
  namespace: demo
spec:
  vaultRef:
    name: vault
  vaultPolicyName: vault-issuer
  policyDocument: |
    path "pki*"                        { capabilities = ["read", "list"] }
    path "pki/sign/example-dot-com"    { capabilities = ["create", "update"] }
    path "pki/issue/example-dot-com"   { capabilities = ["create"] }

---

# vault write auth/kubernetes/role/vault-issuer \
#     bound_service_account_names=vault-issuer \
#     bound_service_account_namespaces=cert-manager \
#     audience="vault://vault-issuer" \
#     policies=vault-issuer \
#     ttl=1m

apiVersion: policy.kubevault.com/v1alpha1
kind: VaultPolicyBinding
metadata:
  name: vault-issuer
  namespace: demo
spec:
  vaultRef:
    name: vault
  vaultRoleName: vault-issuer
  policies:
  - name: vault-issuer
  subjectRef:
    kubernetes:
      serviceAccountNames:
        - "vault-issuer"
      serviceAccountNamespaces:
        - "cert-manager"
      ttl: "1m"
      # maxTTL: "2000"
      # period: "1000"