apiVersion: kubevault.com/v1alpha2
kind: VaultServer
metadata:
  name: vault
  namespace: demo
spec:
  allowedSecretEngines:
    namespaces:
      from: All
  version: "1.13.3"
  replicas: 3
  backend:
    raft:
      storage:
        resources:
          requests:
            storage: 1Gi
  unsealer:
    secretShares: 5
    secretThreshold: 3
    mode:
      kubernetesSecret:
        secretName: vault-keys
  # monitor:
  #   agent: prometheus.io
  #   prometheus:
  #     exporter:
  #       resources: {}
  terminationPolicy: WipeOut
  podTemplate:
    spec:
      readinessProbe:
        failureThreshold: 5
        httpGet:
          path: /v1/sys/health?standbyok=true&perfstandbyok=true
          port: 8200
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 20
        successThreshold: 1
        timeoutSeconds: 15

