apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alone7-client-cert
  namespace: default
spec:
  commonName: www.kubevault.com # root
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: vault-issuer
  secretName: alone7-client-cert
  subject:
    organizationalUnits:
    - client
    organizations:
    - kubedb
  usages:
  - digital signature
  - key encipherment
  - client auth

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: alone7-server-cert
  namespace: default
spec:
  commonName: www.kubevault.com
  dnsNames:
  - '*.alone7-pods.demo.svc'
  - '*.alone7-pods.demo.svc.cluster.local'
  - alone7
  - alone7.demo.svc
  - localhost
  ipAddresses:
  - 127.0.0.1
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: vault-issuer
  secretName: alone7-server-cert
  subject:
    organizationalUnits:
    - server
    organizations:
    - kubedb
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
