apiVersion: engine.kubevault.com/v1alpha1
kind: SecretEngine
metadata:
  name: mg-engine
  namespace: demo
spec:
  vaultRef:
    name: vault
    namespace: demo
  mongodb:
    databaseRef:
      name: repl6
      namespace: demo
    pluginName: mongodb-database-plugin