apiVersion: engine.kubevault.com/v1alpha1
kind: SecretAccessRequest
metadata:
  name: aa-owner
  namespace: demo
spec:
  roleRef:
    kind: MongoDBRole
    name: mg-role
    namespace: demo
  subjects:
    - kind: ServiceAccount
      name: aa-owner
      namespace: demo
      
# kubectl-vault approve secretaccessrequests aa-owner -n demo